import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/styles/globals.css'
import Header from '@/components/core/Header'
import Footer from '@/components/core/Footer'
import config from '@payload-config'
import { getPayload } from 'payload'
import { headers as getHeaders } from 'next/headers.js'
import AdminHelper from '@/components/core/AdminHelper'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headers = await getHeaders()
  const payloadConfig = await config
  const payload = await getPayload({ config: payloadConfig })
  const { user } = await payload.auth({ headers })

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {user && <AdminHelper user={user} />}

        <Header />

        <main className="flex-1 min-h-96">{children}</main>

        <Footer />
      </body>
    </html>
  )
}
